### ISSUE TITLE
Tempestissimo chart is Crashing

### ISSUE THREAD

**Issue by Ayanokouj1-kun** [huoyan1231/A6782852562R78625261C3782939Y738153265E78631865123E#1]
•I've noticed the tempestissimo chart is Crashing even though its locked when you tap it the bug trigger
•some Charts are empty 
- If you want I can share to you my own Modded Arcaea but old mod ver. consists of 612 charts but in return fix these all bugs.😌

**Comment by huoyan1231** [comment]
I know this crash
but I don't want players play Tempestissimo 
so I don't fix it
This is my pirtive Repo so do not publicity it
If you do it ,I will change to pritive

**Comment by Ayanokouj1-kun** [comment]
No problem I know the rules I don't share anything and never will.

**Comment by huoyan1231** [comment]
You can remove tempestissimo in unlocks and songlist
or only remove unlocks
it will fix tempestissimo crash

**Comment by RetardModder** [comment]
http://120.53.117.148:616/latte/14/ this you ip

**Comment by RetardModder** [comment]
Ayanokouj1-kun share page with me thanks

**Comment by RetardModder** [comment]
http://120.53.117.148:616/latte/14/ this you ip

**Comment by Ayanokouj1-kun** [comment]
The way you spoke kinda same with the person ik lol I guess its you
